"""Statistical / structural comparison of component generation: `architectures.py` vs `reservoirpy`.

Addresses Round-2 Item 1 of the performance-gap investigation
(``reservoirpy_research/lyapunov/instructions/26_6_5_performance.md``):

Given the Mackey-Glass benchmark hyperparameters, verify that w_in, bias, and w_res
generated by ``architectures.basic_res / basic_in`` and by ``reservoirpy``'s Reservoir node
are statistically equivalent (spectral radius, nonzero count, value bounds, distribution
uniformity).  The two libraries use different RNG schemes so matrices are **not** element-wise
equal; this test is a structural comparison only.

Usage (from repo root, reservoir venv active)::

    python -m reservoirpy.tests.lyapunov.component_stats
"""

import os
import sys

# ---------------------------------------------------------------------------
# Path setup: mirrors components.py so both reservoir/ and reservoirpy/ resolve.
# ---------------------------------------------------------------------------
sys.path.insert(
    0,
    os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../..")),
)
_RESERVOIR_DIR = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../../../reservoir")
)
if _RESERVOIR_DIR not in sys.path:
    sys.path.insert(0, _RESERVOIR_DIR)

import numpy as np
import scipy.sparse as sp
from scipy import stats

from reservoirpy.tests.lyapunov.esn_test import _N_TRAIN, _load_hp_csv
from reservoirpy.tests.lyapunov.lyapunov_test import _arch_components, build_esn

# architectures may not be importable without the reservoir/ venv; fail loudly if needed.
try:
    import architectures as _arch_mod  # noqa: F401

    _ARCH_AVAILABLE = True
except ImportError as _e:
    _ARCH_AVAILABLE = False
    print(f"[component_stats] WARNING: architectures import failed: {_e}")

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_FIGURES_DIR = os.path.join(_THIS_DIR, "figures")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _to_dense(mat):
    """Convert a scipy sparse matrix or ndarray to a dense ndarray."""
    if sp.issparse(mat):
        return np.asarray(mat.todense())
    return np.asarray(mat)


def _resy_components(hp, input_dim):
    """Extract concrete weight arrays from a reservoirpy Reservoir node.

    Uses ``build_esn`` (the exact construction used by task_g) so the
    extracted matrices match what the model actually trains with.

    Parameters
    ----------
    hp : dict
        Hyperparameter dict from ``_load_hp_csv``.
    input_dim : int
        Number of input dimensions.

    Returns
    -------
    W : ndarray, shape (size, size)
        Dense reservoir weight matrix, spectral radius = ``hp["radius"]``.
    Win : ndarray, shape (size, input_dim)
        Dense input weight matrix, scaled by ``hp["in_scale"]``.
    bias : ndarray, shape (size,)
        Dense bias vector, scaled by ``hp["bias_scale"]``.
    """
    model = build_esn(hp, input_dim, n_train_samples=_N_TRAIN)
    # Trigger initialization with a dummy one-step input to materialise W/Win/bias.
    model.reservoir.initialize(np.zeros((input_dim,)))
    res = model.reservoir
    W = _to_dense(res.W)
    Win = _to_dense(res.Win).reshape(-1, input_dim)
    bias = np.asarray(res.bias).ravel()
    return W, Win, bias


def _spectral_radius(W):
    """Compute spectral radius via full eigendecomposition (same method both sides)."""
    return float(np.max(np.abs(np.linalg.eigvals(W))))


def _ks_uniform(samples, label):
    """Run a KS test for uniformity and print the result.

    For w_res nonzeros: caller should pass scale-normalised values in [0, 1].
    For Win / bias: caller should pass values already in [lo, hi].

    Parameters
    ----------
    samples : array-like
        1-D array of values to test.
    label : str
        Short description printed with the result.

    Returns
    -------
    passed : bool
        True if p-value > 0.05.
    stat : float
        KS statistic.
    pval : float
        KS p-value.
    """
    samples = np.asarray(samples, dtype=float).ravel()
    lo, hi = samples.min(), samples.max()
    # Map to [0, 1] before calling uniform(0, 1) CDF.
    if hi > lo:
        samples_01 = (samples - lo) / (hi - lo)
    else:
        samples_01 = np.zeros_like(samples)
    stat, pval = stats.kstest(samples_01, "uniform")
    passed = pval > 0.05
    flag = "PASS" if passed else "FAIL"
    print(f"    [{flag}]  KS={stat:.4f}  p={pval:.4f}  ({label})")
    return passed, stat, pval


def compare_components(system_name="mackey_glass", save_dir=None, show=False):
    """Compare w_in, bias, and w_res from architectures.py vs reservoirpy.

    Prints a raw-number table (spectral radius, NNZ, value bounds) with
    PASS/FAIL annotations, runs KS uniformity tests, and saves histograms.

    Parameters
    ----------
    system_name : str
        System key; currently only ``"mackey_glass"`` is wired.
    save_dir : str or None
        Directory for the output PNG.  Defaults to
        ``tests/lyapunov/figures/``.
    show : bool
        Call ``plt.show()`` after saving.  Default False (headless-friendly).

    Returns
    -------
    dict
        Raw numbers and PASS flags for every check.
    """
    assert system_name == "mackey_glass", (
        "compare_components is wired for mackey_glass only (input_dim=1)."
    )
    if not _ARCH_AVAILABLE:
        print("[compare_components] skipped: architectures not importable.")
        return {}

    input_dim = 1
    print(f"\n{'=' * 62}")
    print(f"  component_stats: {system_name}  (input_dim={input_dim})")
    print(f"{'=' * 62}")

    # ------------------------------------------------------------------
    # 1. Load HP and generate both sets of matrices
    # ------------------------------------------------------------------
    print("\n[1] Loading hyperparameters …")
    hp = _load_hp_csv(system_name)
    size = int(hp["size"])
    target_sr = float(hp["radius"])
    in_scale = float(hp["in_scale"])
    bias_scale = float(hp["bias_scale"])
    sparse_k = float(hp["sparse"])
    target_nnz = int(round(sparse_k / size * size * size))  # = sparse_k * size
    print(
        f"    size={size}  seed={hp['seed']}  sr={target_sr:.6f}"
        f"  in_scale={in_scale:.6f}  bias_scale={bias_scale:.6f}"
        f"  sparse={sparse_k}  target_nnz≈{target_nnz}"
    )

    print("\n[2] Generating architectures.py matrices (basic_res / basic_in) …")
    W_a, Win_a, bias_a = _arch_components(hp, input_dim)
    W_a = _to_dense(W_a)

    print("\n[3] Generating reservoirpy matrices (Reservoir.initialize) …")
    W_r, Win_r, bias_r = _resy_components(hp, input_dim)

    # ------------------------------------------------------------------
    # 2. Raw-number table
    # ------------------------------------------------------------------
    print(f"\n{'=' * 62}")
    print(f"  RAW NUMBERS")
    print(f"{'=' * 62}")

    sr_a = _spectral_radius(W_a)
    sr_r = _spectral_radius(W_r)
    nnz_a = int(np.count_nonzero(W_a))
    nnz_r = int(np.count_nonzero(W_r))

    wres_nz_a = W_a[W_a != 0]
    wres_nz_r = W_r[W_r != 0]

    win_min_a, win_max_a = float(Win_a.min()), float(Win_a.max())
    win_min_r, win_max_r = float(Win_r.min()), float(Win_r.max())
    bias_min_a, bias_max_a = float(bias_a.min()), float(bias_a.max())
    bias_min_r, bias_max_r = float(bias_r.min()), float(bias_r.max())
    wres_min_a, wres_max_a = float(wres_nz_a.min()), float(wres_nz_a.max())
    wres_min_r, wres_max_r = float(wres_nz_r.min()), float(wres_nz_r.max())

    hdr = f"  {'metric':30s}  {'arch':>12}  {'resy':>12}  {'target':>12}"
    print(hdr)
    print("  " + "-" * (len(hdr) - 2))

    def _row(label, a, r, tgt="—"):
        print(f"  {label:30s}  {a:>12}  {r:>12}  {tgt:>12}")

    _row("W spectral radius", f"{sr_a:.6f}", f"{sr_r:.6f}", f"{target_sr:.6f}")
    _row("W nonzero count", f"{nnz_a}", f"{nnz_r}", f"≈{target_nnz}")
    _row("W nz min (raw)", f"{wres_min_a:.6f}", f"{wres_min_r:.6f}")
    _row("W nz max (raw)", f"{wres_max_a:.6f}", f"{wres_max_r:.6f}")
    print(
        f"  {'':30s}  NOTE: W nz bounds differ by design (radius/rad_w scale factor differs"
        f" per realization)"
    )
    _row("Win min", f"{win_min_a:.6f}", f"{win_min_r:.6f}", f"≈{-in_scale:.6f}")
    _row("Win max", f"{win_max_a:.6f}", f"{win_max_r:.6f}", f"≈{+in_scale:.6f}")
    _row("bias min", f"{bias_min_a:.6f}", f"{bias_min_r:.6f}", f"≈{-bias_scale:.6f}")
    _row("bias max", f"{bias_max_a:.6f}", f"{bias_max_r:.6f}", f"≈{+bias_scale:.6f}")

    # ------------------------------------------------------------------
    # 3. Pass / fail checks
    # ------------------------------------------------------------------
    print(f"\n{'=' * 62}")
    print(f"  PASS / FAIL CHECKS")
    print(f"{'=' * 62}")

    results = {}

    def _check(key, passed, detail):
        flag = "PASS" if passed else "FAIL"
        print(f"  [{flag}]  {key}: {detail}")
        results[key] = passed
        return passed

    # Spectral radius
    sr_tol = 1e-2
    _check(
        "sr_arch ≈ target",
        abs(sr_a - target_sr) < sr_tol,
        f"|{sr_a:.6f} - {target_sr:.6f}| = {abs(sr_a - target_sr):.2e}  (tol {sr_tol:.0e})",
    )
    _check(
        "sr_resy ≈ target",
        abs(sr_r - target_sr) < sr_tol,
        f"|{sr_r:.6f} - {target_sr:.6f}| = {abs(sr_r - target_sr):.2e}  (tol {sr_tol:.0e})",
    )
    _check(
        "sr_arch ≈ sr_resy",
        abs(sr_a - sr_r) < sr_tol,
        f"|{sr_a:.6f} - {sr_r:.6f}| = {abs(sr_a - sr_r):.2e}",
    )

    # NNZ
    nnz_tol = size  # allow ≤ one full row's worth of difference
    _check(
        "nnz_arch ≈ target",
        abs(nnz_a - target_nnz) <= nnz_tol,
        f"|{nnz_a} - {target_nnz}| = {abs(nnz_a - target_nnz)}  (tol {nnz_tol})",
    )
    _check(
        "nnz_resy ≈ target",
        abs(nnz_r - target_nnz) <= nnz_tol,
        f"|{nnz_r} - {target_nnz}| = {abs(nnz_r - target_nnz)}  (tol {nnz_tol})",
    )
    _check(
        "nnz_arch ≈ nnz_resy",
        abs(nnz_a - nnz_r) <= nnz_tol,
        f"|{nnz_a} - {nnz_r}| = {abs(nnz_a - nnz_r)}",
    )

    # Win bounds (5% of in_scale)
    win_tol = 0.05 * in_scale
    _check(
        "Win max_arch ≈ Win max_resy",
        abs(win_max_a - win_max_r) < win_tol,
        f"|{win_max_a:.4f} - {win_max_r:.4f}| = {abs(win_max_a - win_max_r):.2e}"
        f"  (tol {win_tol:.2e})",
    )
    _check(
        "Win min_arch ≈ Win min_resy",
        abs(win_min_a - win_min_r) < win_tol,
        f"|{win_min_a:.4f} - {win_min_r:.4f}| = {abs(win_min_a - win_min_r):.2e}",
    )

    # bias bounds (5% of bias_scale)
    bias_tol = 0.05 * bias_scale
    _check(
        "bias max_arch ≈ bias max_resy",
        abs(bias_max_a - bias_max_r) < bias_tol,
        f"|{bias_max_a:.4f} - {bias_max_r:.4f}| = {abs(bias_max_a - bias_max_r):.2e}"
        f"  (tol {bias_tol:.2e})",
    )
    _check(
        "bias min_arch ≈ bias min_resy",
        abs(bias_min_a - bias_min_r) < bias_tol,
        f"|{bias_min_a:.4f} - {bias_min_r:.4f}| = {abs(bias_min_a - bias_min_r):.2e}",
    )

    # ------------------------------------------------------------------
    # 4. KS uniformity tests
    # ------------------------------------------------------------------
    print(f"\n{'=' * 62}")
    print(f"  KS UNIFORMITY TESTS  (p > 0.05 → uniform)")
    print(f"{'=' * 62}")
    print("  Win entries:")
    ks_win_a = _ks_uniform(Win_a.ravel(), "arch")
    ks_win_r = _ks_uniform(Win_r.ravel(), "resy")
    results["ks_win_arch"] = ks_win_a[0]
    results["ks_win_resy"] = ks_win_r[0]

    print("  bias entries:")
    ks_bias_a = _ks_uniform(bias_a, "arch")
    ks_bias_r = _ks_uniform(bias_r, "resy")
    results["ks_bias_arch"] = ks_bias_a[0]
    results["ks_bias_resy"] = ks_bias_r[0]

    print("  W nonzero entries (scale-normalised by max|·|):")
    wres_nz_a_norm = wres_nz_a / np.max(np.abs(wres_nz_a))
    wres_nz_r_norm = wres_nz_r / np.max(np.abs(wres_nz_r))
    ks_wres_a = _ks_uniform(wres_nz_a_norm, "arch (scale-normalised)")
    ks_wres_r = _ks_uniform(wres_nz_r_norm, "resy (scale-normalised)")
    results["ks_wres_arch"] = ks_wres_a[0]
    results["ks_wres_resy"] = ks_wres_r[0]

    # ------------------------------------------------------------------
    # 5. Histograms
    # ------------------------------------------------------------------
    print(f"\n{'=' * 62}")
    print(f"  HISTOGRAMS")
    print(f"{'=' * 62}")
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        fig, axes = plt.subplots(3, 2, figsize=(10, 9))
        fig.suptitle(
            f"Component distributions: {system_name}  (arch=left, resy=right)",
            fontsize=11,
        )

        def _hist(ax, data, title, color):
            ax.hist(data, bins=40, color=color, alpha=0.75, edgecolor="none")
            ax.set_title(title, fontsize=9)
            ax.set_xlabel("value", fontsize=8)
            ax.set_ylabel("count", fontsize=8)
            ax.tick_params(labelsize=7)

        _hist(axes[0, 0], Win_a.ravel(), f"Win  arch  (n={Win_a.size})", "#4878cf")
        _hist(axes[0, 1], Win_r.ravel(), f"Win  resy  (n={Win_r.size})", "#6acc65")
        _hist(axes[1, 0], bias_a, f"bias arch  (n={bias_a.size})", "#4878cf")
        _hist(axes[1, 1], bias_r, f"bias resy  (n={bias_r.size})", "#6acc65")
        _hist(
            axes[2, 0],
            wres_nz_a,
            f"W nz (raw) arch  (n={wres_nz_a.size})",
            "#4878cf",
        )
        _hist(
            axes[2, 1],
            wres_nz_r,
            f"W nz (raw) resy  (n={wres_nz_r.size})",
            "#6acc65",
        )

        plt.tight_layout()

        if save_dir is None:
            save_dir = _FIGURES_DIR
        os.makedirs(save_dir, exist_ok=True)
        out_path = os.path.join(save_dir, f"component_stats_{system_name}.png")
        plt.savefig(out_path, dpi=120)
        print(f"  Saved: {out_path}")
        results["figure_path"] = out_path

        if show:
            plt.show()
        plt.close(fig)

    except Exception as exc:  # pragma: no cover
        print(f"  [WARN] matplotlib unavailable or failed: {exc}")
        print("  Histograms skipped.")

    # ------------------------------------------------------------------
    # 6. Summary
    # ------------------------------------------------------------------
    n_pass = sum(1 for v in results.values() if v is True)
    n_checks = sum(1 for v in results.values() if isinstance(v, bool))
    print(f"\n{'=' * 62}")
    print(f"  SUMMARY: {n_pass}/{n_checks} checks passed")
    print(f"{'=' * 62}")

    if n_pass == n_checks:
        print(
            "  All checks PASS → component generation is statistically equivalent."
            " Gap lies downstream (state propagation / readout fit); proceed to item 2."
        )
    else:
        failed = [k for k, v in results.items() if v is False]
        print(f"  FAILED checks: {failed}")
        print(
            "  One or more checks FAIL → component generation diverges."
            " Investigate the failed dimensions before proceeding."
        )

    # Store raw numbers for inspection
    results.update(
        {
            "sr_arch": sr_a,
            "sr_resy": sr_r,
            "sr_target": target_sr,
            "nnz_arch": nnz_a,
            "nnz_resy": nnz_r,
            "nnz_target": target_nnz,
            "win_min_arch": win_min_a,
            "win_max_arch": win_max_a,
            "win_min_resy": win_min_r,
            "win_max_resy": win_max_r,
            "bias_min_arch": bias_min_a,
            "bias_max_arch": bias_max_a,
            "bias_min_resy": bias_min_r,
            "bias_max_resy": bias_max_r,
            "wres_nz_min_arch": wres_min_a,
            "wres_nz_max_arch": wres_max_a,
            "wres_nz_min_resy": wres_min_r,
            "wres_nz_max_resy": wres_max_r,
        }
    )
    return results


if __name__ == "__main__":
    compare_components("mackey_glass")
