# Licence: MIT License
# Copyright: Xavier Hinaut (2018) <xavier.hinaut@inria.fr>

import jax
import jax.numpy as jnp

from .node import Node

# Floor applied to the tangent norm before taking its log, to avoid
# ``log(0) = -inf`` when a step is strongly contracting (e.g. saturated tanh).
_NORM_FLOOR = 1e-12


def maximal_lyapunov_exponent(
    node: Node,
    X: jax.Array,
    *,
    warmup: int = 0,
    seed: int = 0,
) -> float:
    """Maximal Lyapunov Exponent (MLE) of a JAX Node driven by input X.

    For an input-driven node this estimates the *conditional* (driven)
    maximal Lyapunov exponent along the trajectory generated by ``X`` -- the
    quantity relevant to the echo state property. It is computed with the
    Benettin algorithm: a random unit tangent vector is evolved through the
    Jacobian of the node's one-step map at each timestep (via :func:`jax.jvp`),
    renormalized after each step to prevent overflow. The average log
    growth-rate converges to the MLE.

    A positive MLE indicates chaotic (diverging) dynamics; a negative MLE
    indicates stable (contracting) dynamics; MLE near zero is the edge of
    chaos.

    Parameters
    ----------
    node : Node
        An initialized JAX Node. Must be stateful (e.g. Reservoir, ES2N,
        LIF, IPReservoir). Stateless readout nodes (Ridge, RLS, LMS) are
        accepted but the result is not meaningful.
    X : jax.Array of shape (T, input_dim)
        Input timeseries driving the node. Must have at least ``warmup + 1``
        timesteps. A non-trivial driving signal (e.g. a chaotic timeseries)
        is recommended; a constant input drives the node to a fixed point and
        the MLE then only reflects the stability of that fixed point.
    warmup : int, default to 0
        Number of initial timesteps used to warm up the node state before
        measuring divergence. These steps are not counted in the MLE average.
        Although it defaults to 0 (for consistency with the rest of the
        library), a non-zero warmup is strongly recommended so that the state
        settles on the attractor and the tangent vector aligns with the
        dominant Lyapunov direction before measurement.
    seed : int, default to 0
        Seed for the initial random tangent vector.

    Returns
    -------
    float
        The estimated Maximal Lyapunov Exponent.

    Raises
    ------
    ValueError
        If the node is not initialized, or if X does not have enough
        timesteps given the warmup parameter.

    Examples
    --------
    >>> import jax.numpy as jnp
    >>> from reservoirpy.datasets import mackey_glass
    >>> from reservoirpy.jax.nodes import Reservoir
    >>> from reservoirpy.jax.observables import maximal_lyapunov_exponent
    >>> reservoir = Reservoir(100, sr=1.2)
    >>> X = jnp.asarray(mackey_glass(2000))
    >>> reservoir.initialize(X[:1])
    >>> mle = maximal_lyapunov_exponent(reservoir, X, warmup=500)
    """
    if not node.initialized:
        raise ValueError(
            "Node must be initialized before computing the Lyapunov exponent. "
            "Call node.initialize(x) or run node(x) once first."
        )

    T = X.shape[0]
    if T - warmup < 1:
        raise ValueError(
            f"X must have more than {warmup} timesteps (warmup) but has {T}."
        )

    # Warmup: evolve state without tracking the tangent vector
    state = node.state
    if warmup > 0:
        def warmup_body(state, x_t):
            return node._step(state, x_t), None

        state, _ = jax.lax.scan(warmup_body, state, X[:warmup])

    # Initialize a random unit tangent vector (same pytree as state)
    key = jax.random.PRNGKey(seed)
    leaves, treedef = jax.tree_util.tree_flatten(state)
    keys = jax.random.split(key, len(leaves))
    tangent_leaves = [jax.random.normal(k, shape=a.shape, dtype=a.dtype) for k, a in zip(keys, leaves)]

    flat_v = jnp.concatenate([jnp.ravel(a) for a in tangent_leaves])
    norm = jnp.linalg.norm(flat_v)
    tangent_leaves = [a / norm for a in tangent_leaves]
    v_init = jax.tree_util.tree_unflatten(treedef, tangent_leaves)

    # Benettin scan: JVP + Gram-Schmidt renormalization at each step
    def scan_body(carry, x_t):
        state, v = carry
        new_state, Jv = jax.jvp(lambda s: node._step(s, x_t), (state,), (v,))

        flat_Jv = jnp.concatenate([jnp.ravel(a) for a in jax.tree_util.tree_leaves(Jv)])
        norm = jnp.linalg.norm(flat_Jv)
        v_next = jax.tree_util.tree_map(lambda a: a / norm, Jv)

        return (new_state, v_next), jnp.log(jnp.maximum(norm, _NORM_FLOOR))

    _, log_growths = jax.lax.scan(scan_body, (state, v_init), X[warmup:])

    return float(jnp.mean(log_growths))
